Add option to reload fstab config with `mount -a`
stuvusIT/fstab pull request #3
Opened 2019-04-23 12:39 UTC by Mr-Pi

2019-04-23 13:05 UTC, SlothOfAnarchy requested changes
I was about to complain that `fstab_reload_method` is not a boolean. @Mr-Pi told me he will add a reboot option today or tomorrow.

2019-04-23 13:05 UTC, SlothOfAnarchy commented on README.md
> +| `fstab_reload_method`     | string                              |                `none`               | Reload method for changes in fstab, valid values are `none`(just update fstab), `reload`(perf
```suggestion
| `fstab_reload_method`     | string                              |                `none`               | Reload method for changes in fstab, valid values are `none`(just update fstab), `reload`(perform `mount -a`)     |
```

2019-04-23 13:05 UTC, SlothOfAnarchy commented on handlers/main.yml
> +- name: Mount all fstab entries `mount -a`
```suggestion
- name: Mount all fstab entries using `mount -a`
```

2019-04-23 13:05 UTC, SlothOfAnarchy commented on handlers/main.yml
> +  listen: fstab_update#
I don't think this `#` is intended
```suggestion
  listen: fstab_update
```

2019-04-23 13:55 UTC, haslersn submitted a review, later dismissed

2019-04-23 13:55 UTC, haslersn commented on README.md
> +| `fstab_reload_method`     | string                              |                `none`               | Reload method for changes in fstab, valid values are `none`(just update fstab), `reload`(perf
`reload` or `remount`?

2019-05-20 19:07 UTC, Mr-Pi commented on README.md
> +| `fstab_reload_method`     | string                              | `remount`                           | Reload method for changes in fstab, currently only `reload` is implemented. `reboot` may be a
remount

2019-05-20 19:23 UTC, SlothOfAnarchy approved these changes

2019-05-20 19:24 UTC, merged